[package]
name = "pyq"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyq"
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pyo3 = { version = "0.23", features = ["extension-module"] }
